### 1. Convert List to 1D Array
Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

### Expected Output:

Original List: [12.23, 13.32, 100, 36.32] One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [5]:
import numpy as np

og_list = [12.23, 13.32, 100, 36.32]

og_arr = np.array(og_list)

print(og_arr)
type(og_arr)

[ 12.23  13.32 100.    36.32]


numpy.ndarray

### 2. Create 3x3 Matrix (2?10)
Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

### Expected Output:

[[ 2 3 4] [ 5 6 7] [ 8 9 10]]

In [12]:
import numpy as np

matrix = np.arange(2, 11).reshape(3,3)

print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### 3. Null Vector (10) & Update Sixth Value
Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

### [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [15]:
import numpy as np

null_vector = np.zeros(10)

null_vector[6] = 11

print(null_vector)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


### 4. Array from 12 to 38
Write a NumPy program to create an array with values ranging from 12 to 38.

### Expected Output:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [16]:
import numpy as np

my_arr = np.arange(12, 38)

print(my_arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


### 5. Convert Array to Float Type
Write a NumPy program to convert an array to a floating type.

### Sample output:

Original array [1, 2, 3, 4]

In [18]:
import numpy as np

og_arr = np.array([1, 2, 3, 4])

og_arr.astype(float)



array([1., 2., 3., 4.])

### 6. Celsius to Fahrenheit Conversion
Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

Sample Array [0, 12, 45.21, 34, 99.91] [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

### Expected Output:

Values in Fahrenheit degrees: [ 0. 12. 45.21 34. 99.91 32. ]

Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

Values in Fahrenheit degrees: [-0. 12. 45.21 34. 99.91 32. ]

In [ ]:
import numpy as np

celsius = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0. ])

fahrenheit = celsius * 9/5 + 32

print("Values in Centigrade degrees:", celsius)
print("Values in Fahrenheit degrees:", np.round(fahrenheit, 2))

Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Fahrenheit degrees: [-0.   12.   45.21 34.   99.91 32.  ]


### 7. Append Values to Array (Do self-tudy)
Write a NumPy program to append values to the end of an array.

### Expected Output:

Original array: [10, 20, 30]

After append values to the end of the array: [10 20 30 40 50 60 70 80 90]

In [30]:
import numpy as np

og_arr = np.array([10, 20, 30])
new_arr = np.append(og_arr, [40, 50, 60, 70, 80, 90])

print(new_arr)


[10 20 30 40 50 60 70 80 90]


### 8. Array Statistical Functions (Do self-tudy)
Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.

In [43]:
import numpy as np

rand_arr = np.arange(10, 21)

# np.mean(rand_arr)
# np.median(rand_arr)
np.std(rand_arr)

3.1622776601683795

### 9 Find min and max
Create a 10x10 array with random values and find the minimum and maximum values.

In [47]:
import numpy as np

rand_arr = np.random.randn(10, 10)

np.min(rand_arr)
np.max(rand_arr)

2.4208451154045623

## 10. Create a 3x3x3 array with random values.

In [48]:
import numpy as np

rand_arr = np.random.randn(3,3,3)

rand_arr

array([[[-0.93453806,  1.08643778,  0.09472479],
        [-1.40059086, -0.17427266, -0.54699904],
        [ 0.82832214,  1.73248882,  0.84483568]],

       [[ 0.54379195,  0.94445251, -1.943098  ],
        [ 0.55570925, -1.53344938,  1.15195193],
        [ 1.45576828, -2.00131195, -1.01021737]],

       [[-0.06617483,  0.21579928, -0.8918086 ],
        [-1.15520268,  0.00953064,  0.34835767],
        [ 0.85377917,  0.14748952, -1.7318241 ]]])